version: "3.1"
services:
  redis:
    image: redis
    ports:
      - 6379:6379
  db:
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: bot
      POSTGRES_USER: bot
      POSTGRES_DB: bot